services:
  image-server:
    image: ghcr.io/amber-bisht/images-bun:latest
    container_name: image-server
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./data/images:/app/public/images
    environment:
      - PORT=4000
      - IMAGE_SERVER_SECRET=${IMAGE_SERVER_SECRET}
      - BASE_URL=${BASE_URL}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
