name: Deploy Image Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Transfer Files to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT || 22 }}
          source: "."
          target: "~/image-server"
          overwrite: true

      - name: Build and Start Container on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            cd ~/image-server
            echo "IMAGE_SERVER_SECRET=${{ secrets.IMAGE_SERVER_SECRET }}" > .env
            echo "BASE_URL=${{ secrets.BASE_URL }}" >> .env
            docker compose build --no-cache
            docker compose up -d --force-recreate
